### ISSUE TITLE
Date and day not aligned

### ISSUE THREAD

**Issue by starfuz** [rudotriton/scriptable-calendar-widget#27]
I’m having an issue where the date and day aren’t being aligned. For instance, today is January 13, which is a Thursday. But on the widget it says that it is January 13, Wednesday. I saw that someone else had the same issue in the “closed” issues section but it was not resolved. 
I’m using the latest version of the code and I’ve tried on multiple devices, so I’m not sure what’s going on. 
If you could help out, that would be great! Thank you!

**Comment by suhfeeyah** [comment]
I’m also saving the same problem. Today is Tuesday 2/15 and startWeekOnSunday is set to false, but the lettering still starts on Sunday, so it shows today as Monday 2/15.
![EA819236-135D-4B71-A1D2-85E7E57622D7](https://user-images.githubusercontent.com/99780087/154190136-3a73e45a-1452-4722-a581-cf7612def90f.jpeg)

**Comment by suhfeeyah** [comment]
Hi! Hoping for a fix?

![11E8D03A-5ED5-48BE-9DBC-68CF82E9A9D5](https://user-images.githubusercontent.com/99780087/159100468-584789c3-88a2-4e7c-b945-2bd962b32793.jpeg)

![1615FB1A-92DD-4455-BC96-BD6765D3B9BF](https://user-images.githubusercontent.com/99780087/159100461-6fe2d97d-b4cc-4028-bbe4-27a8641ec0ed.jpeg)

**Comment by rudotriton** [comment]
It's an interesting issue, because I've not managed to figure out what exactly causes this and I don't think I have ever experienced it myself. Some questions, in order to try to find out actually what causes this:

- does it consistently happen every time you run the script? or only on certain days? or a certain time of day, e.g. maybe only between 12 and 2 am?
- date and time settings:
  - 24h or 12h time
  - timezone
- language and region
- and if you happen to have a screenshot then maybe at what time was the screenshot taken

---
@suhfeeyah Is the first screenshot with startWeekOnSunday, and the 2nd one without it, i.e. everything, but the top weekday row, is what you'd expect to see?

**Comment by suhfeeyah** [comment]
@rudotriton To answer your questions:

1. It does happen every time I run the script.
2. Date and time settings are currently 12h, automatically set to Cupertino (Pacific time)
3. Language is English, region is United States
4. Screenshots were taken at 5:53 PM for the first (startWeekOnSunday set to true) and 5:55 PM for the second (startWeekOnSunday set to false).

Everything else is accurate in terms of the numbering of the month. It is just the weekday row that is inaccurate.

**Comment by suhfeeyah** [comment]
Thank you so much, it's working perfectly!
