### ISSUE TITLE
active allday events with highlight color

### ISSUE THREAD

**Issue by FIetch** [rudotriton/scriptable-calendar-widget#8]
Hi,
how can i change it to highlight the allday events if the starting date is not today?
if i make a event from today about 6 days long, it only show today in highlight event color with this code
one day later the color is gone

+ const isEventToday = new Date().getDate() === event.startDate.getDate();
  // event title
  addWidgetTextLine(eventLine, event.title, {
- color,
+ color: isEventToday ? "#ffff00" : color,
  font: Font.mediumSystemFont(14),

**Comment by rudotriton** [comment]
I've updated the script. It was an oversight. An allday event that lasts multiple days will now highlight all days that it spans. Let me know if that fixes your issue.

**Comment by FIetch** [comment]
yes, i saw it. I tried to use ur new one yesterday but i didn´t get my resulst that i want. Also with ur updated just today.
But i changed something in my/your old Script version and now it works :)

I just change the event.startDate.getDate to event.endDate.getDate

const isEventToday = new Date().getDate() === event.**end**Date.getDate();

**Comment by rudotriton** [comment]
I didn't have an update yesterday, but I also think that using the endDate would not fix all your problems since it still counts the event on a single day or only a single day would be highlighted.

When I first wrote it I had not considered a multi day event. What the last fix does is that if you have an event that started today (Dec 9) and lasted for 3 days (Dec 9, 10, 11), then all 3 days would receive a highlight. The event's data would show 9th as the startDate, but the endDate is actually 12th.

**Comment by FIetch** [comment]
do i need to edit the highlight color? I just "download" ur new script, made an all day event from yesterday to today and it wont be highlighted as i want.

and i mean that i used ur new script yesterday which u updated cause its oversight and i used the update from today.

**Comment by FIetch** [comment]
You are right, my solution dont wirk correct.
If my all day Event Starts today, ist wont be highligted anymore...

**Comment by FIetch** [comment]
I have now used your new script again and I can't get the event highlighted to me if the event started in the past. If the event starts today, it will be highlighted.

**Comment by rudotriton** [comment]
It is possible that you won't see the color because it is very light. At most, on a day with a single event, the highlight color will be 20% of the full intensity which is really light. In some cases it can be even less  than 20%.

https://github.com/rudotriton/scriptable-calendar-widget/blob/8cf926d587d18ab9b98548a4899765251036acc5/calendar.js#L257

This line does the calculation. If you think it is too light for you, you can use a fixed value:

```diff
-  intensity = intensity > 0.2 ? 0.2 : intensity;

- return { eventCounts, intensity };
+ return { eventCounts, intensity: 0.4 };
```

If you have a dark background, you possibly want it even higher than 0.4.

For example, below, 8 and 10 have a 0.2 highlight which is barely visible.

<p align="center" >
    <img width="450" alt="scriptable calendar" src ="https://user-images.githubusercontent.com/14181026/101653495-09b75c00-3a48-11eb-8254-6085414c977f.png">
</p>

**Comment by FIetch** [comment]
![3647E967-D14B-47DF-90A2-0E85E597685D](https://user-images.githubusercontent.com/59744922/101654189-821a1f00-3a40-11eb-82bb-040fe7f23507.jpeg)

I Wang to Highlight the Text, Not in the calender view

**Comment by rudotriton** [comment]
Oh, I think I understand you now. I remember you previously wanted to highlight the titles for the events that are today. 

If you go back to this line and change it to also include all day events then this should do it
```
const isEventToday = new Date().getDate() === event.startDate.getDate() || event.isAllDay;
```

What it says now is that: if the date today is the same as the event's startDate OR if the event is an all day event.

For example this one starts on the 7th:

<p align="center" >
    <img width="350" alt="scriptable calendar" src ="https://user-images.githubusercontent.com/14181026/101659020-45edbb00-3a4e-11eb-9a79-6acf771d4384.png">
</p>

**Comment by FIetch** [comment]
Now also future events are highlighted

**Comment by rudotriton** [comment]
`const isEventToday =
    new Date().getDate() === event.startDate.getDate() ||
    (event.isAllDay && event.startDate.getDate() < new Date().getDate());`

Something like this then?

<p align="center" >
    <img width="350" alt="scriptable calendar" src ="https://user-images.githubusercontent.com/14181026/101675075-f9ac7600-3a61-11eb-8203-590eef4684d7.png"">
</p>

**Comment by FIetch** [comment]
I think now it looks great 😁

**Comment by rudotriton** [comment]
Glad I could help
